---

- name: Verify
  hosts: all
  become: True
  gather_facts: True
  vars_files:
    - metrics.yml
  vars:
    libvirt_exporter_url: "http://localhost:9177/metrics"
  tasks:
    - name: Assert that libvirt_exporter is serving
      uri:
        url: "{{ libvirt_exporter_url }}"
        status_code: 200

    - name: Get /metrics content from libvirt_eporter
      command: "prom2json {{ libvirt_exporter_url }}"
      register: libvirt_exporter_response

    - name: Prettify libvirt_exporter_result
      set_fact:
        libvirt_exporter_metrics: "{{ libvirt_exporter_response.stdout | from_json }}"

    - name: Assert that all metrics are present
      assert:
        that: "libvirt_exporter_metrics | selectattr('name', 'equalto', item.name) | length"
      loop: "{{ metrics }}"

    - name: Assert that all metrics metric have necessary type
      vars:
        libvirt_up_metric: "{{ libvirt_exporter_metrics | selectattr('name', 'equalto', item.name) | first }}"
      assert:
        that: "libvirt_up_metric.type == item.type"
      loop: "{{ metrics }}"
